import { cn } from 'ui/src/lib/utils';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';

import 'ui/src/css/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-slate-200 text-slate-900')}>
        <div className="max-w-md mx-auto min-h-screen bg-white relative">
          <nav className="p-4 flex items-center justify-center w-full bg-yellow-400">
            <Image src="/zis.png" alt="Logo" width={32} height={32} />
          </nav>
          <div className="pb-16">{children}</div>
          <div className="h-16 bg-white w-full fixed bottom-0 left-0 right-0 max-w-md mx-auto shadow-t-sm border-t border-t-slate-100"></div>
        </div>
      </body>
    </html>
  );
}
